---
- name: Build AWX Docker Images
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Get version from SCM if not explicitly provided
      command: make version-for-buildyml
      args:
        chdir: '../../'
      register: scm_version
      failed_when: not scm_version.stdout
      when: awx_version is not defined

    - name: Set awx_version
      set_fact:
        awx_version: "{{ scm_version.stdout }}"
      when: awx_version is not defined

    - name: Set awx_docker_version with + replaced by _
      set_fact:
        awx_docker_version: "{{ awx_version | replace('+', '_') }}"

    - include_role:
        name: dockerfile
    - include_role:
        name: image_build
    - include_role:
        name: image_push
      when: push | default(false) | bool
