"""GitHub App Installation Access Token Credential Plugin.

This module defines a credential plugin for making use of the
GitHub Apps mechanism, allowing authentication via GitHub App
installation-scoped access tokens.

This file has been adapted from
https://github.com/ansible/awx-plugins/blob/37a1e756ef01567f2c92bba7476342d3e02f8577/src/awx_plugins/credentials/github_app.py
(Apache 2.0 License) and modified to fit into the ascender/awx codebase and credential plugin framework.
"""

from .plugin import CredentialPlugin

from django.utils.translation import gettext_lazy as _

from github import (
    Auth as Auth,
    Github,
)
from github.Consts import DEFAULT_BASE_URL as PUBLIC_GH_API_URL
from github.GithubException import (
    BadAttributeException,
    GithubException,
    UnknownObjectException,
)


github_app_inputs = {
    'fields': [
        {
            'id': 'github_api_url',
            'label': _('GitHub API endpoint URL'),
            'type': 'string',
            'help_text': _(
                'Specify the GitHub API URL here. In the case of an Enterprise: '
                'https://gh.your.org/api/v3 (self-hosted) '
                'or https://api.SUBDOMAIN.ghe.com (cloud)',
            ),
            'default': 'https://api.github.com',
        },
        {
            'id': 'app_or_client_id',
            'label': _('GitHub App ID or Client ID'),
            'type': 'string',
            'help_text': _(
                'The GitHub App ID or Client ID created by the GitHub Admin. '
                'Example App ID: 1121547, Client ID: Iv23likIfIXeZTb5GCAA '
                'found on https://github.com/settings/apps/ '
                'required for creating a JWT token for authentication.',
            ),
        },
        {
            'id': 'install_id',
            'label': _('GitHub App Installation ID'),
            'type': 'string',
            'help_text': _(
                'The Installation ID from the GitHub App installation '
                'generated by the GitHub Admin. '
                'Example: 59980338 extracted from the installation link '
                'https://github.com/settings/installations/59980338 '
                'required for creating a limited GitHub app token.',
            ),
        },
        {
            'id': 'private_rsa_key',
            'label': _('RSA Private Key'),
            'type': 'string',
            'format': 'ssh_private_key',
            'secret': True,
            'multiline': True,
            'help_text': _(
                'Paste the contents of the PEM file that the GitHub Admin '
                'provided to you with the app and installation IDs.',
            ),
        },
    ],
    'metadata': [
        {
            'id': 'description',
            'label': _('Description (Optional)'),
            'type': 'string',
            'help_text': _('To be removed after UI is updated'),
        },
    ],
    'required': ['app_or_client_id', 'install_id', 'private_rsa_key'],
}


def extract_github_app_install_token(
    **kwargs,
):
    """Generate a GitHub App Installation access token.

    :raises ValueError: If authentication fails or parameters are invalid.
    :raises RuntimeError: If an unexpected error occurs during token generation.
    """
    github_api_url = kwargs.get('github_api_url', '')
    app_or_client_id = kwargs.get('app_or_client_id')
    private_rsa_key = kwargs.get('private_rsa_key')
    install_id = kwargs.get('install_id')

    auth = Auth.AppAuth(
        app_id=str(app_or_client_id),
        private_key=private_rsa_key,
    ).get_installation_auth(installation_id=int(install_id))

    Github(
        auth=auth,
        base_url=github_api_url or PUBLIC_GH_API_URL,
    )

    doc_url = (
        'See https://docs.github.com/rest/reference/apps'
        '#create-an-installation-access-token-for-an-app'
    )
    app_install_context = (
        f'app_or_client_id: {app_or_client_id}, install_id: {install_id}'
    )

    try:
        return auth.token
    except UnknownObjectException as github_install_not_found_exc:
        raise ValueError(
            'Failed to retrieve a GitHub installation token from '
            f'{github_api_url!s} using {app_install_context!s}. '
            f'Is the app installed? {doc_url!s}.'
            f'\n\n{github_install_not_found_exc!s}',
        ) from github_install_not_found_exc
    except GithubException as pygithub_catchall_exc:
        raise RuntimeError(
            'An unexpected error happened while talking to GitHub API @ '
            f'{github_api_url!s} ({app_install_context!s}). '
            'Is the app or client ID correct? And the private RSA key? '
            f'{doc_url!s}.\n\n{pygithub_catchall_exc!s}',
        ) from pygithub_catchall_exc
    except BadAttributeException as github_broken_exc:
        raise RuntimeError(
            f'Broken GitHub @ {github_api_url!s} with '
            f'{app_install_context!s}. It is a bug, please report it to the '
            f'developers.\n\n{github_broken_exc!s}',
        ) from github_broken_exc


github_app_plugin = CredentialPlugin(
    'GitHub App Installation Access Token Lookup',
    inputs=github_app_inputs,
    backend=extract_github_app_install_token,
)
