# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 19:49
from __future__ import unicode_literals

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth2_provider.generators
import oauth2_provider.models
import re


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0024_v330_create_user_session_membership'),
    ]
    run_before = [
        # As of this migration, OAuth2Application and OAuth2AccessToken are models in main app
        # Grant and RefreshToken models are still in the oauth2_provider app and reference
        # the app and token models, so these must be created before the oauth2_provider models
        ('oauth2_provider', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2Application',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=100, unique=True)),
                (
                    'redirect_uris',
                    models.TextField(blank=True, help_text='Allowed URIs list, space separated'),
                ),
                ('client_type', models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], max_length=32)),
                (
                    'authorization_grant_type',
                    models.CharField(
                        choices=[
                            ('authorization-code', 'Authorization code'),
                            ('implicit', 'Implicit'),
                            ('password', 'Resource owner password-based'),
                            ('client-credentials', 'Client credentials'),
                        ],
                        max_length=32,
                    ),
                ),
                ('client_secret', models.CharField(blank=True, db_index=True, default=oauth2_provider.generators.generate_client_secret, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('skip_authorization', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('logo_data', models.TextField(default='', editable=False, validators=[django.core.validators.RegexValidator(re.compile('.*'))])),
                (
                    'user',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_oauth2application', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'verbose_name': 'application',
            },
        ),
        migrations.CreateModel(
            name='OAuth2AccessToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('scope', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('last_used', models.DateTimeField(default=None, editable=False, null=True)),
                (
                    'application',
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_oauth2accesstoken', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'verbose_name': 'access token',
            },
        ),
        # OAuth2RefreshToken and OAuth2IDToken are created here, in the same
        # migration as the application and access token they point at, rather
        # than in a migration of their own. They are swapped in through
        # OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL and OAUTH2_PROVIDER_ID_TOKEN_MODEL,
        # so every historical state that mentions OAuth2AccessToken.
        # source_refresh_token or .id_token resolves those names into main. 0041
        # adds the first of those fields, 0183 the second, and oauth2_provider's
        # own 0004 adds both to its (swapped out) AccessToken, so the models have
        # to exist before any of them or the state cannot be built:
        #   ValueError: The field main.OAuth2AccessToken.source_refresh_token was
        #   declared with a lazy reference to 'main.oauth2refreshtoken', but app
        #   'main' doesn't provide model 'oauth2refreshtoken'.
        # This migration already runs before oauth2_provider's, see run_before
        # above, and it is applied on every existing install, so putting them
        # here needs no new ordering and cannot make an applied migration depend
        # on an unapplied one. The tables themselves are created for existing
        # databases by 0214.
        migrations.CreateModel(
            name='OAuth2IDToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jti', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='JWT Token ID')),
                ('expires', models.DateTimeField(verbose_name='expires')),
                ('scope', models.TextField(blank=True, verbose_name='scope')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                (
                    'application',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                        verbose_name='application',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'ID token',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OAuth2RefreshToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.TextField(verbose_name='token')),
                ('token_checksum', oauth2_provider.models.TokenChecksumField(max_length=64, verbose_name='token checksum')),
                ('token_family', models.UUIDField(blank=True, editable=False, null=True, verbose_name='token family')),
                ('resource', oauth2_provider.models.ResourceJSONField(blank=True, default=list, verbose_name='resource')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('revoked', models.DateTimeField(null=True, verbose_name='revoked')),
                (
                    'access_token',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='refresh_token',
                        to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL,
                        verbose_name='access token',
                    ),
                ),
                (
                    'application',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='application'),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='user'
                    ),
                ),
            ],
            options={
                'verbose_name': 'refresh token',
                'ordering': ('id',),
                'abstract': False,
                'indexes': [models.Index(fields=['token_family'], name='main_oauth2_token_f_981dfd_idx')],
                'unique_together': {('token_checksum', 'revoked')},
            },
        ),
        migrations.AddField(
            model_name='activitystream',
            name='o_auth2_access_token',
            field=models.ManyToManyField(to='main.OAuth2AccessToken', blank=True),
        ),
        migrations.AddField(
            model_name='activitystream',
            name='o_auth2_application',
            field=models.ManyToManyField(to='main.OAuth2Application', blank=True),
        ),
    ]
