# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-10 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0070_v350_gce_instance_id'),
    ]

    operations = [
        # Note: Fact model indexes were already removed/empty before this migration
        # No need to clear index_together as the model is being deleted
        migrations.RemoveField(
            model_name='fact',
            name='host',
        ),
        migrations.DeleteModel(
            name='Fact',
        ),
    ]
