# Generated by Django 3.2.16 on 2023-05-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0183_pre_django_upgrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentialtype",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ssh", "Machine"),
                    ("vault", "Vault"),
                    ("net", "Network"),
                    ("scm", "Source Control"),
                    ("cloud", "Cloud"),
                    ("registry", "Container Registry"),
                    ("token", "Personal Access Token"),
                    ("external", "External"),
                    ("kubernetes", "Kubernetes"),
                    ("galaxy", "Galaxy/Automation Hub"),
                    ("cryptography", "Cryptography"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="inventorysource",
            name="source",
            field=models.CharField(
                choices=[
                    ("file", "File, Directory or Script"),
                    (
                        "constructed",
                        "Template additional groups and hostvars at runtime",
                    ),
                    ("scm", "Sourced from a Project"),
                    ("ec2", "Amazon EC2"),
                    ("gce", "Google Compute Engine"),
                    ("azure_rm", "Microsoft Azure Resource Manager"),
                    ("vmware", "VMware vCenter"),
                    ("openstack", "OpenStack"),
                ],
                default=None,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryupdate",
            name="source",
            field=models.CharField(
                choices=[
                    ("file", "File, Directory or Script"),
                    (
                        "constructed",
                        "Template additional groups and hostvars at runtime",
                    ),
                    ("scm", "Sourced from a Project"),
                    ("ec2", "Amazon EC2"),
                    ("gce", "Google Compute Engine"),
                    ("azure_rm", "Microsoft Azure Resource Manager"),
                    ("vmware", "VMware vCenter"),
                    ("openstack", "OpenStack"),
                ],
                default=None,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="scm_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Manual"),
                    ("git", "Git"),
                    ("svn", "Subversion"),
                    ("archive", "Remote Archive"),
                ],
                default="",
                help_text="Specifies the source control system used to store the project.",
                max_length=8,
                verbose_name="SCM Type",
            ),
        ),
        migrations.AlterField(
            model_name="projectupdate",
            name="scm_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Manual"),
                    ("git", "Git"),
                    ("svn", "Subversion"),
                    ("archive", "Remote Archive"),
                ],
                default="",
                help_text="Specifies the source control system used to store the project.",
                max_length=8,
                verbose_name="SCM Type",
            ),
        ),
    ]
