# Generated by Django 3.2.16 on 2023-06-13 21:17
from django.db import migrations, models
class Migration(migrations.Migration):
    def delete_some_rows(apps, scheme_editor):
        module = apps.get_model('main', 'credentialtype').objects.filter(name="Insights").delete()
        module = apps.get_model('main', 'credentialtype').objects.filter(name="Red Hat Virtualization").delete()
        module = apps.get_model('main', 'credentialtype').objects.filter(name="Red Hat Ansible Automation Platform").delete()
        module = apps.get_model('main', 'credentialtype').objects.filter(name="Red Hat Satellite 6").delete()
    dependencies = [
        ('main', '0183_auto_20230522_2151'),
    ]
    operations = [
        migrations.AlterField(
            model_name='credentialtype',
            name='kind',
            field=models.CharField(choices=[('ssh', 'Machine'), ('vault', 'Vault'), ('net', 'Network'), ('scm', 'Source Control'), ('cloud', 'Cloud'), ('registry', 'Container Registry'), ('token', 'Personal Access Token'), ('insights', 'Insights'), ('external', 'External'), ('kubernetes', 'Kubernetes'), ('galaxy', 'Galaxy/Automation Hub'), ('cryptography', 'Cryptography')], max_length=32),
        ),
        migrations.RunPython(delete_some_rows)
    ]