# Generated by Django 5.2.9 on 2026-01-26 07:16

import awx.main.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0193_alter_inventorysource_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionEnvironmentBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('description', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=512, unique=True)),
                (
                    'image',
                    models.CharField(
                        blank=True, default='', help_text='The name for the built execution environment image', max_length=1024, verbose_name='Image Name'
                    ),
                ),
                (
                    'tag',
                    models.CharField(
                        blank=True, default='latest', help_text='The tag for the built execution environment image', max_length=1024, verbose_name='Image Tag'
                    ),
                ),
                (
                    'definition',
                    models.TextField(blank=True, default='', help_text='Ansible builder execution environment definition', verbose_name='Definition'),
                ),
                (
                    'admin_role',
                    awx.main.fields.ImplicitRoleField(
                        editable=False,
                        null='True',
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_role=['organization.execution_environment_builder_admin_role', 'singleton:system_administrator'],
                        related_name='+',
                        to='main.role',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%s(class)s_created+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'credential',
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text='Container registry credential for pushing the built image',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)ss',
                        to='main.credential',
                    ),
                ),
                (
                    'modified_by',
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%s(class)s_modified+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text='The organization used to determine access to this execution environment builder.',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)ss',
                        to='main.organization',
                    ),
                ),
                (
                    'read_role',
                    awx.main.fields.ImplicitRoleField(
                        editable=False,
                        null='True',
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_role=['organization.auditor_role', 'singleton:system_auditor', 'admin_role'],
                        related_name='+',
                        to='main.role',
                    ),
                ),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='activitystream',
            name='execution_environment_builder',
            field=models.ManyToManyField(blank=True, to='main.executionenvironmentbuilder'),
        ),
    ]
