# Generated by Django 3.2.16 on 2026-01-23 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0193_alter_inventorysource_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTemplateMetric',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='job_template_metric', serialize=False, to='main.jobtemplate')),
                ('name', models.CharField(help_text='Job template name for identification', max_length=512, unique=True)),
                ('first_job', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the job template was first used')),
                ('last_job', models.DateTimeField(db_index=True, help_text='When the job template was last used')),
                ('total_jobs', models.BigIntegerField(default=0, help_text='How many times the job template was used')),
                ('total_seconds', models.BigIntegerField(default=0, help_text='Total seconds of all job executions')),
                ('successful_jobs', models.BigIntegerField(default=0, help_text='How many times jobs from this template succeeded')),
                ('successful_seconds', models.BigIntegerField(default=0, help_text='Total seconds of successful job executions')),
                ('failed_jobs', models.BigIntegerField(default=0, help_text='How many times jobs from this template failed')),
                ('failed_seconds', models.BigIntegerField(default=0, help_text='Total seconds of failed job executions')),
                ('canceled_jobs', models.BigIntegerField(default=0, help_text='How many times jobs from this template were canceled')),
                ('canceled_seconds', models.BigIntegerField(default=0, help_text='Total seconds of canceled job executions')),
            ],
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='JobTemplateMetricsSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_job', models.DateTimeField(blank=True, null=True, help_text='When the first job template was first used')),
                ('last_job', models.DateTimeField(blank=True, null=True, help_text='When the last job template was last used')),
                ('total_jobs', models.BigIntegerField(default=0, help_text='Total number of job template executions')),
                ('total_seconds', models.BigIntegerField(default=0, help_text='Total seconds of all job executions across all templates')),
                ('successful_jobs', models.BigIntegerField(default=0, help_text='Total successful jobs across all templates')),
                ('successful_seconds', models.BigIntegerField(default=0, help_text='Total seconds of successful job executions across all templates')),
                ('failed_jobs', models.BigIntegerField(default=0, help_text='Total failed jobs across all templates')),
                ('failed_seconds', models.BigIntegerField(default=0, help_text='Total seconds of failed job executions across all templates')),
                ('canceled_jobs', models.BigIntegerField(default=0, help_text='Total canceled jobs across all templates')),
                ('canceled_seconds', models.BigIntegerField(default=0, help_text='Total seconds of canceled job executions across all templates')),
            ],
            options={
                'verbose_name': 'Job Template Metrics Summary',
                'verbose_name_plural': 'Job Template Metrics Summary',
            },
        ),
    ]
