# Generated by Django 5.2.9 on 2026-01-26 21:04

import awx.main.fields
import awx.main.models.notifications
import django.db.models.deletion
from django.db import migrations, models, connection


def setup_event_partitioning(apps, schema_editor):
    """Set up partitioning for ExecutionEnvironmentBuilderBuildEvent table"""
    tblname = 'main_executionenvironmentbuilderbuildevent'
    unpartitioned_tblname = f'_unpartitioned_{tblname}'
    
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_name = %s
            )
        """, [tblname])
        
        if not cursor.fetchone()[0]:
            # Table doesn't exist yet, it will be created by the CreateModel operation
            return
        
        # Check if unpartitioned table already exists (from previous failed/rollback attempt)
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_name = %s
            )
        """, [unpartitioned_tblname])
        
        if cursor.fetchone()[0]:
            # Unpartitioned table already exists, drop it and start fresh
            cursor.execute(f'DROP TABLE IF EXISTS {unpartitioned_tblname}')
            
        # Mark existing table as unpartitioned
        cursor.execute(f'ALTER TABLE {tblname} RENAME TO {unpartitioned_tblname}')

        # Create a temporary table to use as schema reference
        cursor.execute(f'CREATE TABLE tmp_{tblname} (LIKE {unpartitioned_tblname} INCLUDING ALL)')

        # Drop primary key constraint
        cursor.execute(f'ALTER TABLE tmp_{tblname} DROP CONSTRAINT tmp_{tblname}_pkey')

        # Create partitioned parent table
        cursor.execute(
            f'CREATE TABLE {tblname} '
            f'(LIKE tmp_{tblname} INCLUDING ALL) '
            f'PARTITION BY RANGE(job_created);'
        )

        cursor.execute(f'DROP TABLE tmp_{tblname}')

        # Recreate primary key constraint with partition key
        cursor.execute(f'ALTER TABLE ONLY {tblname} ADD CONSTRAINT {tblname}_pkey_new PRIMARY KEY (id, job_created);')


def setup_event_partitioning_sqlite(apps, schema_editor):
    # SQLite doesn't support partitioning, just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0194_executionenvironmentbuilder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionEnvironmentBuilderBuild',
            fields=[
                (
                    'unifiedjob_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='main.unifiedjob',
                    ),
                ),
                (
                    'execution_environment_builder',
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='main.executionenvironmentbuilder'
                    ),
                ),
            ],
            bases=('main.unifiedjob', awx.main.models.notifications.JobNotificationMixin),
        ),
        migrations.CreateModel(
            name='ExecutionEnvironmentBuilderBuildEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'event',
                    models.CharField(
                        choices=[
                            ('runner_on_failed', 'Host Failed'),
                            ('runner_on_start', 'Host Started'),
                            ('runner_on_ok', 'Host OK'),
                            ('runner_on_error', 'Host Failure'),
                            ('runner_on_skipped', 'Host Skipped'),
                            ('runner_on_unreachable', 'Host Unreachable'),
                            ('runner_on_no_hosts', 'No Hosts Remaining'),
                            ('runner_on_async_poll', 'Host Polling'),
                            ('runner_on_async_ok', 'Host Async OK'),
                            ('runner_on_async_failed', 'Host Async Failure'),
                            ('runner_item_on_ok', 'Item OK'),
                            ('runner_item_on_failed', 'Item Failed'),
                            ('runner_item_on_skipped', 'Item Skipped'),
                            ('runner_retry', 'Host Retry'),
                            ('runner_on_file_diff', 'File Difference'),
                            ('playbook_on_start', 'Playbook Started'),
                            ('playbook_on_notify', 'Running Handlers'),
                            ('playbook_on_include', 'Including File'),
                            ('playbook_on_no_hosts_matched', 'No Hosts Matched'),
                            ('playbook_on_no_hosts_remaining', 'No Hosts Remaining'),
                            ('playbook_on_task_start', 'Task Started'),
                            ('playbook_on_vars_prompt', 'Variables Prompted'),
                            ('playbook_on_setup', 'Gathering Facts'),
                            ('playbook_on_import_for_host', 'internal: on Import for Host'),
                            ('playbook_on_not_import_for_host', 'internal: on Not Import for Host'),
                            ('playbook_on_play_start', 'Play Started'),
                            ('playbook_on_stats', 'Playbook Complete'),
                            ('debug', 'Debug'),
                            ('verbose', 'Verbose'),
                            ('deprecated', 'Deprecated'),
                            ('warning', 'Warning'),
                            ('system_warning', 'System Warning'),
                            ('error', 'Error'),
                        ],
                        max_length=100,
                    ),
                ),
                ('event_data', awx.main.fields.JSONBlob(blank=True, default=dict)),
                ('failed', models.BooleanField(default=False, editable=False)),
                ('changed', models.BooleanField(default=False, editable=False)),
                ('uuid', models.CharField(default='', editable=False, max_length=1024)),
                ('playbook', models.CharField(default='', editable=False, max_length=1024)),
                ('play', models.CharField(default='', editable=False, max_length=1024)),
                ('role', models.CharField(default='', editable=False, max_length=1024)),
                ('task', models.CharField(default='', editable=False, max_length=1024)),
                ('counter', models.PositiveIntegerField(default=0, editable=False)),
                ('stdout', models.TextField(default='', editable=False)),
                ('verbosity', models.PositiveIntegerField(default=0, editable=False)),
                ('start_line', models.PositiveIntegerField(default=0, editable=False)),
                ('end_line', models.PositiveIntegerField(default=0, editable=False)),
                ('created', models.DateTimeField(default=None, editable=False, null=True)),
                ('modified', models.DateTimeField(db_index=True, default=None, editable=False)),
                ('job_created', models.DateTimeField(editable=False, null=True)),
                ('parent_uuid', models.CharField(default='', editable=False, max_length=1024)),
                (
                    'execution_environment_builder_build',
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='execution_environment_builder_build_events',
                        to='main.executionenvironmentbuilderbuild',
                    ),
                ),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='UnpartitionedExecutionEnvironmentBuilderBuildEvent',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.executionenvironmentbuilderbuildevent',),
        ),
        migrations.AddIndex(
            model_name='executionenvironmentbuilderbuildevent',
            index=models.Index(fields=['execution_environment_builder_build', 'job_created', 'event'], name='main_execut_executi_e9bdb1_idx'),
        ),
        migrations.AddIndex(
            model_name='executionenvironmentbuilderbuildevent',
            index=models.Index(fields=['execution_environment_builder_build', 'job_created', 'uuid'], name='main_execut_executi_083198_idx'),
        ),
        migrations.AddIndex(
            model_name='executionenvironmentbuilderbuildevent',
            index=models.Index(fields=['execution_environment_builder_build', 'job_created', 'counter'], name='main_execut_executi_03d2ab_idx'),
        ),
        migrations.RunPython(setup_event_partitioning, setup_event_partitioning_sqlite),
    ]
