# Generated by Django 5.2.14 on 2026-06-10 19:29

import oauth2_provider.models
from django.db import migrations, models


def compute_token_checksums(apps, schema_editor):
    """
    Touch every existing access token so TokenChecksumField.pre_save computes
    the checksum (mirrors oauth2_provider migration 0012_add_token_checksum).
    """
    OAuth2AccessToken = apps.get_model('main', 'OAuth2AccessToken')
    for access_token in OAuth2AccessToken._default_manager.iterator():
        access_token.save(update_fields=['token_checksum'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0197_add_federated_inventory_kind'),
    ]

    operations = [
        # Stage 1: add the checksum column as nullable (no unique constraint yet,
        # existing rows would all collide on a static default).
        migrations.AddField(
            model_name='oauth2accesstoken',
            name='token_checksum',
            field=oauth2_provider.models.TokenChecksumField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='token',
            field=models.TextField(),
        ),
        # Stage 2: populate checksums for existing tokens.
        migrations.RunPython(compute_token_checksums, migrations.RunPython.noop),
        # Stage 3: tighten to the final unique, indexed, non-null definition.
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='token_checksum',
            field=oauth2_provider.models.TokenChecksumField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='oauth2application',
            name='allowed_origins',
            field=models.TextField(blank=True, default='', help_text='Allowed origins list to enable CORS, space separated'),
        ),
        migrations.AddField(
            model_name='oauth2application',
            name='hash_client_secret',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='oauth2application',
            name='post_logout_redirect_uris',
            field=models.TextField(blank=True, default='', help_text='Allowed Post Logout URIs list, space separated'),
        ),
    ]
