# Generated by Django 5.2.15 on 2026-06-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0198_oauth2accesstoken_token_checksum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancegroup',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='receptoraddress',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='workflowjobtemplatenode',
            options={'ordering': ('id',)},
        ),
    ]
