# Generated by Django 5.2.15 on 2026-06-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0198_oauth2accesstoken_token_checksum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowjobnode',
            name='prior_run_elapsed',
            field=models.FloatField(
                default=None, editable=False, help_text="Elapsed time (seconds) of this node's job in the run it was carried forward from.", null=True
            ),
        ),
        migrations.AddField(
            model_name='workflowjobnode',
            name='prior_run_succeeded',
            field=models.BooleanField(
                default=False,
                help_text="Set when a workflow is relaunched from a failed node: the node's job succeeded in the prior run, so it is carried forward as already-successful. It spawns no new job, but the scheduler treats it as a successful parent so its success/always paths are still traversed.",
            ),
        ),
    ]
