# Generated by Django 5.2.15 on 2026-07-02 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0200_add_list_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowJobNodeConditionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'trigger',
                    models.CharField(
                        blank=True,
                        choices=[('success', 'On success'), ('failure', 'On failure'), ('always', 'Always')],
                        default='success',
                        help_text='Parent job outcome required before the condition is evaluated.',
                        max_length=16,
                    ),
                ),
                (
                    'artifact_key',
                    models.CharField(blank=True, default='', help_text='Artifact key (produced via set_stats) on the parent job to evaluate.', max_length=512),
                ),
                (
                    'operator',
                    models.CharField(
                        blank=True,
                        choices=[('eq', 'Equals'), ('ne', 'Not equals')],
                        default='eq',
                        help_text='Comparison operator applied to the artifact value.',
                        max_length=16,
                    ),
                ),
                (
                    'expected_value',
                    models.TextField(
                        blank=True,
                        default='',
                        help_text='Value the artifact is compared against. Interpreted as JSON when possible, otherwise as a plain string.',
                    ),
                ),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_links_from', to='main.workflowjobnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_links_to', to='main.workflowjobnode')),
            ],
            options={
                'unique_together': {('from_node', 'to_node')},
            },
        ),
        migrations.AddField(
            model_name='workflowjobnode',
            name='condition_nodes',
            field=models.ManyToManyField(
                blank=True,
                related_name='%(class)ss_condition',
                through='main.WorkflowJobNodeConditionLink',
                through_fields=('from_node', 'to_node'),
                to='main.workflowjobnode',
            ),
        ),
        migrations.CreateModel(
            name='WorkflowJobTemplateNodeConditionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'trigger',
                    models.CharField(
                        blank=True,
                        choices=[('success', 'On success'), ('failure', 'On failure'), ('always', 'Always')],
                        default='success',
                        help_text='Parent job outcome required before the condition is evaluated.',
                        max_length=16,
                    ),
                ),
                (
                    'artifact_key',
                    models.CharField(blank=True, default='', help_text='Artifact key (produced via set_stats) on the parent job to evaluate.', max_length=512),
                ),
                (
                    'operator',
                    models.CharField(
                        blank=True,
                        choices=[('eq', 'Equals'), ('ne', 'Not equals')],
                        default='eq',
                        help_text='Comparison operator applied to the artifact value.',
                        max_length=16,
                    ),
                ),
                (
                    'expected_value',
                    models.TextField(
                        blank=True,
                        default='',
                        help_text='Value the artifact is compared against. Interpreted as JSON when possible, otherwise as a plain string.',
                    ),
                ),
                (
                    'from_node',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_links_from', to='main.workflowjobtemplatenode'),
                ),
                (
                    'to_node',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_links_to', to='main.workflowjobtemplatenode'),
                ),
            ],
            options={
                'unique_together': {('from_node', 'to_node')},
            },
        ),
        migrations.AddField(
            model_name='workflowjobtemplatenode',
            name='condition_nodes',
            field=models.ManyToManyField(
                blank=True,
                related_name='%(class)ss_condition',
                through='main.WorkflowJobTemplateNodeConditionLink',
                through_fields=('from_node', 'to_node'),
                to='main.workflowjobtemplatenode',
            ),
        ),
    ]
