# Generated by Django 5.2.15 on 2026-07-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0200_add_list_ordering'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobhostsummary',
            index=models.Index(fields=['host', '-id'], name='main_jobhostsumm_host_id_desc'),
        ),
    ]
