# Generated by Django 5.2.15 on 2026-07-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0201_workflowjobnodeconditionlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='webhook_key',
            field=models.CharField(blank=True, help_text='Shared secret that the webhook service will use to sign requests', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='webhook_ref_filter',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Only sync the project when the webhook ref matches this fnmatch pattern (e.g. refs/heads/main or refs/heads/release-*). When empty, any push or tag event triggers a sync.',
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='webhook_service',
            field=models.CharField(
                blank=True,
                choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket_dc', 'BitBucket DataCenter')],
                help_text='Service that webhook requests will be accepted from',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='webhook_guid',
            field=models.CharField(blank=True, help_text='Unique identifier of the event that triggered this webhook', max_length=128),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='webhook_service',
            field=models.CharField(
                blank=True,
                choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket_dc', 'BitBucket DataCenter')],
                help_text='Service that the webhook request that triggered this update came from',
                max_length=16,
            ),
        ),
    ]
