# Generated by Django 5.2.15 on 2026-07-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0203_workflow_node_retries'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_slice_pinned_hosts',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Comma separated list of host names to include in every slice of a sliced job, in addition to the hosts of the slice itself. Useful when a play targets a coordinating host, such as localhost, that all slices depend on. Names are matched exactly against inventory hosts; groups and patterns are not supported. Has no effect unless the job is sliced.',
            ),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='job_slice_pinned_hosts',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Comma separated list of host names to include in every slice of a sliced job, in addition to the hosts of the slice itself. Useful when a play targets a coordinating host, such as localhost, that all slices depend on. Names are matched exactly against inventory hosts; groups and patterns are not supported. Has no effect unless the job is sliced.',
            ),
        ),
    ]
