# Generated by Django 5.2.15 on 2026-07-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0204_job_slice_pinned_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='instance_group_routing_var',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Name of an inventory variable used to route hosts to instance groups at launch. When set, hosts are grouped by the value of this variable (host variables win over group variables) and the launch spawns one job per group, restricted to its hosts and assigned to the instance group named by the value. Hosts without the variable run in an extra job with the normal instance group selection. Launch fails if a value does not name an existing instance group or the launching user lacks use permission on it. Cannot be combined with job slicing.',
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='instance_group_routing_var',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Name of an inventory variable used to route hosts to instance groups at launch. When set, hosts are grouped by the value of this variable (host variables win over group variables) and the launch spawns one job per group, restricted to its hosts and assigned to the instance group named by the value. Hosts without the variable run in an extra job with the normal instance group selection. Launch fails if a value does not name an existing instance group or the launching user lacks use permission on it. Cannot be combined with job slicing.',
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name='job',
            name='instance_group_routing_value',
            field=models.TextField(
                default=None,
                editable=False,
                help_text="If created by instance group routing, the routing variable value that selected this job's bucket of hosts. An empty string means the bucket of hosts that do not resolve the variable. Null when the job was not routed.",
                null=True,
            ),
        ),
    ]
