# Generated by Django 5.2.15 on 2026-07-14 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0206_jobhostsummary_main_jobhostsumm_host_id_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowapproval',
            name='on_timeout',
            field=models.CharField(
                blank=True,
                choices=[('deny', 'Deny'), ('approve', 'Approve')],
                default='deny',
                help_text='Whether the approval node is automatically approved or denied when the timeout expires.',
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='required_approvals',
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                help_text='The number of distinct users that must approve before the node is considered approved. A single denial always denies the node.',
            ),
        ),
        migrations.AddField(
            model_name='workflowapprovaltemplate',
            name='on_timeout',
            field=models.CharField(
                blank=True,
                choices=[('deny', 'Deny'), ('approve', 'Approve')],
                default='deny',
                help_text='Whether the approval node is automatically approved or denied when the timeout expires.',
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name='workflowapprovaltemplate',
            name='required_approvals',
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                help_text='The number of distinct users that must approve before the node is considered approved. A single denial always denies the node.',
            ),
        ),
        migrations.CreateModel(
            name='WorkflowApprovalVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                (
                    'vote',
                    models.CharField(
                        choices=[('approve', 'Approve'), ('deny', 'Deny')],
                        editable=False,
                        help_text='Whether this user approved or denied the workflow approval.',
                        max_length=7,
                    ),
                ),
                ('comment', models.TextField(blank=True, default='', editable=False, help_text='Optional comment the user submitted along with their vote.')),
                (
                    'workflow_approval_name',
                    models.CharField(
                        blank=True,
                        default='',
                        editable=False,
                        help_text='Name of the approval node at the time of the vote, kept after the approval is deleted.',
                        max_length=512,
                    ),
                ),
                (
                    'workflow_job_id',
                    models.IntegerField(
                        default=None,
                        editable=False,
                        help_text='ID of the workflow job the approval belonged to, kept after the approval is deleted.',
                        null=True,
                    ),
                ),
                (
                    'workflow_job_name',
                    models.CharField(
                        blank=True,
                        default='',
                        editable=False,
                        help_text='Name of the workflow job the approval belonged to, kept after the approval is deleted.',
                        max_length=512,
                    ),
                ),
                (
                    'user_name',
                    models.CharField(
                        blank=True,
                        default='',
                        editable=False,
                        help_text='Username of the voter at the time of the vote, kept after the user is deleted.',
                        max_length=512,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='workflow_approval_votes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'workflow_approval',
                    models.ForeignKey(
                        default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='main.workflowapproval'
                    ),
                ),
            ],
            options={
                'ordering': ('-created',),
                'constraints': [models.UniqueConstraint(fields=('workflow_approval', 'user'), name='unique_workflow_approval_vote_per_user')],
            },
        ),
    ]
