# Generated by Django 5.2.16 on 2026-08-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0207_approval_quorum_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skip_tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='skip_tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
