# Generated by Django 5.2.15 on 2026-09-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0211_remove_host_last_job_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='allow_deletes_while_in_use',
            field=models.BooleanField(
                default=False,
                help_text='If enabled, hosts can be deleted from this inventory while jobs are running against it. By default those deletions are rejected until the running jobs finish.',
            ),
        ),
    ]
