# Generated by Django 6.1.1 on 2026-09-06 14:04

import django.db.models.deletion
import oauth2_provider.generators
import oauth2_provider.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0212_inventory_allow_deletes_while_in_use'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_ID_TOKEN_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2accesstoken',
            name='resource',
            field=oauth2_provider.models.ResourceJSONField(blank=True, default=list, verbose_name='resource'),
        ),
        migrations.AddField(
            model_name='oauth2application',
            name='cimd_expires_at',
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text='When the cached Client ID Metadata Document should be re-fetched',
                null=True,
                verbose_name='CIMD expires at',
            ),
        ),
        migrations.AddField(
            model_name='oauth2application',
            name='registration_source',
            field=models.CharField(
                choices=[('manual', 'Manual'), ('dcr', 'Dynamic Client Registration'), ('cimd', 'Client ID Metadata Document')],
                default='manual',
                help_text='How this application was registered (manual, DCR per RFC 7591, or CIMD)',
                max_length=32,
                verbose_name='registration source',
            ),
        ),
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='application',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='application'
            ),
        ),
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='expires',
            field=models.DateTimeField(verbose_name='expires'),
        ),
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='id_token',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='access_token',
                to=settings.OAUTH2_PROVIDER_ID_TOKEN_MODEL,
                verbose_name='ID token',
            ),
        ),
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='source_refresh_token',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='refreshed_access_token',
                to=settings.OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL,
                verbose_name='source refresh token',
            ),
        ),
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='token',
            field=models.TextField(verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='token_checksum',
            field=oauth2_provider.models.TokenChecksumField(db_index=True, max_length=64, unique=True, verbose_name='token checksum'),
        ),
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='oauth2application',
            name='algorithm',
            field=models.CharField(
                blank=True,
                choices=[('', 'No OIDC support'), ('RS256', 'RSA with SHA-2 256'), ('HS256', 'HMAC with SHA-2 256')],
                default='',
                max_length=5,
                verbose_name='algorithm',
            ),
        ),
        migrations.AlterField(
            model_name='oauth2application',
            name='allowed_origins',
            field=models.TextField(blank=True, default='', help_text='Allowed origins list to enable CORS, space separated', verbose_name='allowed origins'),
        ),
        migrations.AlterField(
            model_name='oauth2application',
            name='client_id',
            field=models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=255, unique=True, verbose_name='client ID'),
        ),
        migrations.AlterField(
            model_name='oauth2application',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='oauth2application',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='oauth2application',
            name='post_logout_redirect_uris',
            field=models.TextField(
                blank=True, default='', help_text='Allowed Post Logout URIs list, space separated', verbose_name='post logout redirect URIs'
            ),
        ),
        migrations.AlterField(
            model_name='oauth2application',
            name='redirect_uris',
            field=models.TextField(blank=True, help_text='Allowed URIs list, space separated', verbose_name='redirect URIs'),
        ),
        migrations.AlterField(
            model_name='oauth2application',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='oauth2application',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(app_label)s_%(class)s',
                to=settings.AUTH_USER_MODEL,
                verbose_name='user',
            ),
        ),
    ]
