# Generated by Django 6.1.1 on 2026-09-07 23:32

import django.db.models.deletion
import oauth2_provider.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Both models are swapped in through OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL and
    # OAUTH2_PROVIDER_ID_TOKEN_MODEL, so every historical state mentioning
    # OAuth2AccessToken.source_refresh_token or .id_token now resolves those
    # names into main. 0041 adds the first field and 0183 the second, so the
    # models have to exist by then or the state cannot be built at all:
    #   ValueError: The field main.OAuth2AccessToken.source_refresh_token was
    #   declared with a lazy reference to 'main.oauth2refreshtoken', but app
    #   'main' doesn't provide model 'oauth2refreshtoken'.
    # Hence the early dependency and run_before rather than following 0213.
    # OAuth2Application and OAuth2AccessToken, which both point at, come from
    # 0025, so 0040 is late enough.
    dependencies = [
        ('main', '0040_v330_unifiedjob_controller_node'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    run_before = [
        ('main', '0041_v330_update_oauth_refreshtoken'),
        # oauth2_provider's own 0001 creates its (now swapped out) AccessToken
        # with the same two foreign keys, so its state needs the models too.
        # main/0025 already carries a run_before for this migration.
        ('oauth2_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2IDToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jti', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='JWT Token ID')),
                ('expires', models.DateTimeField(verbose_name='expires')),
                ('scope', models.TextField(blank=True, verbose_name='scope')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                (
                    'application',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                        verbose_name='application',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'ID token',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OAuth2RefreshToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.TextField(verbose_name='token')),
                ('token_checksum', oauth2_provider.models.TokenChecksumField(max_length=64, verbose_name='token checksum')),
                ('token_family', models.UUIDField(blank=True, editable=False, null=True, verbose_name='token family')),
                ('resource', oauth2_provider.models.ResourceJSONField(blank=True, default=list, verbose_name='resource')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('revoked', models.DateTimeField(null=True, verbose_name='revoked')),
                (
                    'access_token',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='refresh_token',
                        to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL,
                        verbose_name='access token',
                    ),
                ),
                (
                    'application',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='application'),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='user'
                    ),
                ),
            ],
            options={
                'verbose_name': 'refresh token',
                'ordering': ('id',),
                'abstract': False,
                'indexes': [models.Index(fields=['token_family'], name='main_oauth2_token_f_981dfd_idx')],
                'unique_together': {('token_checksum', 'revoked')},
            },
        ),
    ]
