# Generated by Django 6.1.1 on 2026-09-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0214_oauth2_token_models_into_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentialtype",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ssh", "Machine"),
                    ("vault", "Vault"),
                    ("net", "Network"),
                    ("scm", "Source Control"),
                    ("cloud", "Cloud"),
                    ("registry", "Container Registry"),
                    ("token", "Personal Access Token"),
                    ("external", "External"),
                    ("kubernetes", "Kubernetes"),
                    ("galaxy", "Galaxy/Automation Hub"),
                    ("cryptography", "Cryptography"),
                ],
                max_length=32,
            ),
        ),
    ]
