# Generated by Django 6.1.1 on 2026-09-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0216_rename_towerschedulestate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hostmetricsummarymonthly",
            name="license_capacity",
        ),
        migrations.RemoveField(
            model_name="hostmetricsummarymonthly",
            name="license_consumed",
        ),
        migrations.AlterField(
            model_name="hostmetric",
            name="deleted",
            field=models.BooleanField(
                default=False,
                help_text="Boolean flag saying whether the host is deleted and therefore no longer counted as automated",
            ),
        ),
        migrations.AlterField(
            model_name="hostmetricsummarymonthly",
            name="hosts_added",
            field=models.IntegerField(
                default=0,
                help_text="How many hosts were first automated in the associated month",
            ),
        ),
        migrations.AlterField(
            model_name="hostmetricsummarymonthly",
            name="hosts_deleted",
            field=models.IntegerField(
                default=0,
                help_text="How many hosts were deleted in the associated month",
            ),
        ),
    ]
