# Generated by Django 5.2.15 on 2026-09-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0219_source_project_update_set_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="allow_jobs_while_syncing",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, jobs and ad hoc commands against this inventory start while it is being synced, using the hosts it had before the sync. By default they wait for the sync to finish. A job whose template updates the inventory on launch still waits for that update.",
            ),
        ),
    ]
