# Generated by Django 6.1.1 on 2026-09-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0220_workflow_allow_overwrite_flow_vars_on_relaunch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("grafana", "Grafana"),
                    ("irc", "IRC"),
                    ("matrix", "Matrix"),
                    ("mattermost", "Mattermost"),
                    ("pagerduty", "Pagerduty"),
                    ("rocketchat", "Rocket.Chat"),
                    ("slack", "Slack"),
                    ("twilio", "Twilio"),
                    ("webhook", "Webhook"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("grafana", "Grafana"),
                    ("irc", "IRC"),
                    ("matrix", "Matrix"),
                    ("mattermost", "Mattermost"),
                    ("pagerduty", "Pagerduty"),
                    ("rocketchat", "Rocket.Chat"),
                    ("slack", "Slack"),
                    ("twilio", "Twilio"),
                    ("webhook", "Webhook"),
                ],
                max_length=32,
            ),
        ),
    ]
