# Generated by Django 6.1.1 on 2026-10-01 18:14

import ascender.main.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0225_jobtemplate_prevent_relaunch"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdHocCommandInstanceGroupMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(db_index=True, default=None, null=True),
                ),
                (
                    "adhoccommand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.adhoccommand",
                    ),
                ),
                (
                    "instancegroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.instancegroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="adhoccommand",
            name="instance_groups",
            field=ascender.main.fields.OrderedManyToManyField(
                blank=True,
                editable=False,
                help_text="Instance groups picked when the command was launched. When empty, the inventory and organization instance groups are used.",
                related_name="ad_hoc_command_instance_groups",
                through="main.AdHocCommandInstanceGroupMembership",
                to="main.instancegroup",
            ),
        ),
    ]
