# Generated by Django 6.1.1 on 2026-10-01 06:40

import ascender.main.fields
import ascender.main.models.notifications
import ascender.main.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

EVENT_TABLE = 'main_executionenvironmentbuilderbuildevent'


def partition_build_events(apps, schema_editor):
    # Every other event table became partitioned in 0144. This one is new and
    # empty, so it is simply made again as a partitioned table, keeping the
    # columns, defaults, identity and checks CreateModel gave it and putting its
    # indexes back under the names Django knows them by. Partitions are added
    # per hour as builds are created, as for the others.
    tmp = f'tmp_{EVENT_TABLE}'
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f'ALTER TABLE {EVENT_TABLE} RENAME TO {tmp}')
        cursor.execute(
            'SELECT indexdef FROM pg_indexes WHERE schemaname = current_schema() AND tablename = %s AND indexname <> %s',
            [tmp, f'{EVENT_TABLE}_pkey'],
        )
        index_definitions = [row[0] for row in cursor.fetchall()]
        cursor.execute(
            f'CREATE TABLE {EVENT_TABLE} (LIKE {tmp} INCLUDING DEFAULTS INCLUDING IDENTITY INCLUDING CONSTRAINTS INCLUDING STORAGE INCLUDING COMMENTS) '
            'PARTITION BY RANGE(job_created)'
        )
        cursor.execute(f'DROP TABLE {tmp}')
        # constraints on a partitioned table must include the partition key
        cursor.execute(f'ALTER TABLE ONLY {EVENT_TABLE} ADD CONSTRAINT {EVENT_TABLE}_pkey_new PRIMARY KEY (id, job_created)')
        for definition in index_definitions:
            cursor.execute(definition.replace(f' ON {tmp} ', f' ON {EVENT_TABLE} ').replace(f'.{tmp} ', f'.{EVENT_TABLE} '))


def unpartition_build_events(apps, schema_editor):
    # Dropping the model removes the partitioned table along with its partitions.
    pass


def find_execution_environment_files(apps, schema_editor):
    # Projects list their definition files the way they list playbooks, as of
    # their last sync. Fill that in from what is on disk here now, so builders
    # can be set up before every project has been synced again.
    import os

    from django.conf import settings as django_settings

    from ascender.main.utils.ansible import skip_directory

    Project = apps.get_model('main', 'Project')
    for project in Project.objects.exclude(scm_type='').exclude(local_path='').iterator():
        project_path = os.path.join(django_settings.PROJECTS_ROOT, project.local_path)
        if not os.path.isdir(project_path):
            continue
        found = []
        for dirpath, dirnames, filenames in os.walk(project_path):
            if skip_directory(dirpath):
                continue
            for filename in filenames:
                if filename in ('execution-environment.yml', 'execution-environment.yaml'):
                    found.append(os.path.relpath(os.path.join(dirpath, filename), project_path))
        if found:
            project.execution_environment_files = sorted(found, key=str.lower)
            project.save(update_fields=['execution_environment_files'])


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0225_jobtemplate_prevent_relaunch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='execution_environment_files',
            field=models.JSONField(
                blank=True,
                default=list,
                editable=False,
                help_text='List of ansible-builder execution environment definition files found in the project',
                verbose_name='Execution Environment Files',
            ),
        ),
        migrations.CreateModel(
            name='ExecutionEnvironmentBuilder',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('description', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=512, unique=True)),
                (
                    'image',
                    models.CharField(
                        help_text='The image to tag the built execution environment as and push it to, including the container registry.',
                        max_length=1024,
                        validators=[ascender.main.validators.validate_container_image_name],
                        verbose_name='Image Name',
                    ),
                ),
                (
                    'tag',
                    models.CharField(
                        default='latest',
                        help_text='The tag for the built execution environment image.',
                        max_length=128,
                        validators=[
                            django.core.validators.RegexValidator(
                                '^[\\w][\\w.-]{0,127}$',
                                message='Enter a valid image tag.',
                            )
                        ],
                        verbose_name='Image Tag',
                    ),
                ),
                (
                    'execution_environment_file',
                    models.CharField(
                        help_text='Path to the ansible-builder execution environment definition file within the project.',
                        max_length=1024,
                        verbose_name='Execution Environment File',
                    ),
                ),
                (
                    'admin_role',
                    ascender.main.fields.ImplicitRoleField(
                        editable=False,
                        null='True',
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_role=[
                            'organization.execution_environment_admin_role',
                            'singleton:system_administrator',
                        ],
                        related_name='+',
                        to='main.role',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%s(class)s_created+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'credential',
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text='Container registry credential used to push the built image.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)ss',
                        to='main.credential',
                    ),
                ),
                (
                    'modified_by',
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%s(class)s_modified+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='The organization used to determine access to this execution environment builder.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)ss',
                        to='main.organization',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        default=None,
                        help_text='The project that contains the execution environment definition file.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)ss',
                        to='main.project',
                    ),
                ),
                (
                    'read_role',
                    ascender.main.fields.ImplicitRoleField(
                        editable=False,
                        null='True',
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_role=[
                            'organization.auditor_role',
                            'singleton:system_auditor',
                            'admin_role',
                        ],
                        related_name='+',
                        to='main.role',
                    ),
                ),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='activitystream',
            name='execution_environment_builder',
            field=models.ManyToManyField(blank=True, to='main.executionenvironmentbuilder'),
        ),
        migrations.CreateModel(
            name='ExecutionEnvironmentBuilderBuild',
            fields=[
                (
                    'unifiedjob_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='main.unifiedjob',
                    ),
                ),
                (
                    'scm_revision',
                    models.CharField(
                        blank=True,
                        default='',
                        editable=False,
                        help_text='The SCM Revision from the project the image was built from.',
                        max_length=1024,
                        verbose_name='SCM Revision',
                    ),
                ),
                (
                    'execution_environment_builder',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='builds',
                        to='main.executionenvironmentbuilder',
                    ),
                ),
                (
                    'source_project_update',
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        help_text='The project update that synced the project for this build, if one was needed.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='scm_execution_environment_builder_builds',
                        to='main.projectupdate',
                    ),
                ),
            ],
            options={
                'ordering': ('id',),
            },
            bases=(
                'main.unifiedjob',
                ascender.main.models.notifications.JobNotificationMixin,
            ),
        ),
        migrations.CreateModel(
            name='ExecutionEnvironmentBuilderBuildEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'event',
                    models.CharField(
                        choices=[
                            ('runner_on_failed', 'Host Failed'),
                            ('runner_on_start', 'Host Started'),
                            ('runner_on_ok', 'Host OK'),
                            ('runner_on_error', 'Host Failure'),
                            ('runner_on_skipped', 'Host Skipped'),
                            ('runner_on_unreachable', 'Host Unreachable'),
                            ('runner_on_no_hosts', 'No Hosts Remaining'),
                            ('runner_on_async_poll', 'Host Polling'),
                            ('runner_on_async_ok', 'Host Async OK'),
                            ('runner_on_async_failed', 'Host Async Failure'),
                            ('runner_item_on_ok', 'Item OK'),
                            ('runner_item_on_failed', 'Item Failed'),
                            ('runner_item_on_skipped', 'Item Skipped'),
                            ('runner_retry', 'Host Retry'),
                            ('runner_on_file_diff', 'File Difference'),
                            ('playbook_on_start', 'Playbook Started'),
                            ('playbook_on_notify', 'Running Handlers'),
                            ('playbook_on_include', 'Including File'),
                            ('playbook_on_no_hosts_matched', 'No Hosts Matched'),
                            ('playbook_on_no_hosts_remaining', 'No Hosts Remaining'),
                            ('playbook_on_task_start', 'Task Started'),
                            ('playbook_on_vars_prompt', 'Variables Prompted'),
                            ('playbook_on_setup', 'Gathering Facts'),
                            (
                                'playbook_on_import_for_host',
                                'internal: on Import for Host',
                            ),
                            (
                                'playbook_on_not_import_for_host',
                                'internal: on Not Import for Host',
                            ),
                            ('playbook_on_play_start', 'Play Started'),
                            ('playbook_on_stats', 'Playbook Complete'),
                            ('debug', 'Debug'),
                            ('verbose', 'Verbose'),
                            ('deprecated', 'Deprecated'),
                            ('warning', 'Warning'),
                            ('system_warning', 'System Warning'),
                            ('error', 'Error'),
                        ],
                        max_length=100,
                    ),
                ),
                ('event_data', ascender.main.fields.JSONBlob(blank=True, default=dict)),
                ('failed', models.BooleanField(default=False, editable=False)),
                ('changed', models.BooleanField(default=False, editable=False)),
                ('uuid', models.CharField(default='', editable=False, max_length=1024)),
                (
                    'playbook',
                    models.CharField(default='', editable=False, max_length=1024),
                ),
                ('play', models.CharField(default='', editable=False, max_length=1024)),
                ('role', models.CharField(default='', editable=False, max_length=1024)),
                ('task', models.CharField(default='', editable=False, max_length=1024)),
                ('counter', models.PositiveIntegerField(default=0, editable=False)),
                ('stdout', models.TextField(default='', editable=False)),
                ('verbosity', models.PositiveIntegerField(default=0, editable=False)),
                ('start_line', models.PositiveIntegerField(default=0, editable=False)),
                ('end_line', models.PositiveIntegerField(default=0, editable=False)),
                (
                    'created',
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                (
                    'modified',
                    models.DateTimeField(db_index=True, default=None, editable=False),
                ),
                ('parent_uuid', models.CharField(default='', editable=False, max_length=1024)),
                ('job_created', models.DateTimeField(editable=False, null=True)),
                (
                    'execution_environment_builder_build',
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='execution_environment_builder_build_events',
                        to='main.executionenvironmentbuilderbuild',
                    ),
                ),
            ],
            options={
                'ordering': ('pk',),
                'indexes': [
                    models.Index(
                        fields=[
                            'execution_environment_builder_build',
                            'job_created',
                            'event',
                        ],
                        name='main_execut_executi_e9bdb1_idx',
                    ),
                    models.Index(
                        fields=[
                            'execution_environment_builder_build',
                            'job_created',
                            'uuid',
                        ],
                        name='main_execut_executi_083198_idx',
                    ),
                    models.Index(
                        fields=[
                            'execution_environment_builder_build',
                            'job_created',
                            'counter',
                        ],
                        name='main_execut_executi_03d2ab_idx',
                    ),
                ],
            },
        ),
        migrations.RunPython(partition_build_events, unpartition_build_events),
        migrations.RunPython(find_execution_environment_files, migrations.RunPython.noop),
    ]
