# Copyright (c) 2026 Ctrl IQ, Inc.
# All Rights Reserved.
"""
``awx-manage generate_setting_types``: write awx/settings/typed.py from the settings.
"""

import os

from awx.settings.typed import settings
from django.core.management.base import BaseCommand

from awx.conf import settings_registry

#: What a registered setting's field says it holds, for the ones whose value is
#: None and so says nothing itself.
FIELD_TYPES = {
    'IntegerField': 'int',
    'BooleanField': 'bool',
    'CharField': 'str',
    'URLField': 'str',
    'StringListField': 'list[str]',
    'DictField': 'dict[str, Any]',
    'ListField': 'list[Any]',
    'ChoiceField': 'str',
}

HEADER = '''# Copyright (c) 2026 Ctrl IQ, Inc.
# All Rights Reserved.
"""
The settings, with types.

``django.conf.settings`` is a LazySettings, so a checker makes nothing of
``settings.SOMETHING``: every read is Unknown, and a misspelled name is not an
error but a line that raises the first time it runs. Describing the settings
here gives ty both, with no plugin and no second checker, because it is ordinary
typing rather than anything Django specific.

Import from here rather than from django.conf::

    from awx.settings.typed import settings

At run time it is the same object, so nothing changes but what a checker sees.

Generated by ``awx-manage generate_setting_types`` and held to the settings by
``awx/conf/tests/functional/test_setting_types.py``, so a setting added without
a type here fails rather than quietly going back to Unknown.
"""

from typing import Any, Protocol

from django.conf import settings as _django_settings


class AscenderSettings(Protocol):
    """Every setting this deployment answers, and what it holds."""

'''

FOOTER = '''


#: The settings object itself. The cast is the one unchecked step, and it is the
#: whole point: LazySettings proxies to whatever the settings modules defined, so
#: only this line can say what that is.
settings: AscenderSettings = _django_settings  # type: ignore[assignment]
'''


def setting_names():
    """
    Every setting name the settings object answers to.

    dir() is not enough on its own: a setting that only the conf registry
    provides, CUSTOM_LOGO and LICENSE among them, answers to getattr without
    appearing there, so the registry is unioned in. Leaving them out is how the
    first version of this file missed eight settings that views read.
    """
    # Three named url settings are not declared anywhere: URLModificationMiddleware
    # creates them when the middleware chain is built, so nothing sees them until
    # it has been. Building it here is what keeps them out of Unknown.
    from awx.main.middleware import URLModificationMiddleware

    try:
        URLModificationMiddleware(lambda request: None)
    except Exception:
        pass  # already built in this process, which is fine

    names = {n for n in dir(settings) if n.isupper() and not n.startswith('_')}
    names |= set(settings_registry.get_registered_settings())
    return sorted(names)


def type_of(name):
    """
    What one setting holds, as a type expression.

    Taken from the value where the value says something, and from the field the
    setting is registered with where it is None and does not.
    """
    try:
        value = getattr(settings, name)
    except Exception:
        return 'Any'
    if isinstance(value, bool):
        return 'bool'
    if isinstance(value, int):
        return 'int'
    if isinstance(value, float):
        return 'float'
    if isinstance(value, str):
        return 'str'
    if isinstance(value, list):
        return 'list[Any]'
    if isinstance(value, tuple):
        return 'tuple[Any, ...]'
    if isinstance(value, dict):
        # Not every settings dict is keyed by a string. NAMED_URL_GRAPH is keyed
        # by model class, and saying str there makes an ordinary lookup an error.
        if value and all(isinstance(k, str) for k in value):
            return 'dict[str, Any]'
        return 'dict[Any, Any]'
    if value is None and name in settings_registry.get_registered_settings():
        try:
            field = type(settings_registry.get_setting_field(name)).__name__
        except Exception:
            return 'Any'
        declared = FIELD_TYPES.get(field)
        return '%s | None' % declared if declared else 'Any'
    return 'Any'


def render():
    """The whole of awx/settings/typed.py, as text."""
    body = '\n'.join('    %s: %s' % (name, type_of(name)) for name in setting_names())
    return HEADER + body + FOOTER


class Command(BaseCommand):
    help = 'Write awx/settings/typed.py from the settings this deployment holds.'

    def add_arguments(self, parser):
        parser.add_argument('--check', action='store_true', help='Say whether the file is in step, and write nothing.')

    def handle(self, *args, **options):
        path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '..', '..', 'settings', 'typed.py')
        path = os.path.normpath(path)
        text = render()
        if options['check']:
            current = open(path).read() if os.path.exists(path) else ''
            if current != text:
                self.stdout.write('awx/settings/typed.py is out of step; run awx-manage generate_setting_types')
                raise SystemExit(1)
            self.stdout.write('awx/settings/typed.py is in step with the settings.')
            return
        open(path, 'w').write(text)
        self.stdout.write('wrote %s, %d settings' % (path, len(setting_names())))
