#!/usr/bin/env python3
"""Regenerate sphinx_ascender_theme/static/css/pygments-dark.css.

Light mode uses the "ansible" Pygments style from theme.conf. Sphinx emits
only one pygments.css, so the dark variant is generated here and scoped to
html[data-theme="dark"].

Run from docs/docsite: python tools/gen-pygments-dark.py
"""

from pathlib import Path

from pygments.formatters import HtmlFormatter

STYLE = "github-dark"
SELECTOR = 'html[data-theme="dark"]'
OUTPUT = Path(__file__).resolve().parent.parent / (
    "sphinx_ascender_theme/static/css/pygments-dark.css"
)

HEADER = f'''/*! Generated by tools/gen-pygments-dark.py from the Pygments "{STYLE}"
 * style. Do not hand-edit.
 */

'''


def main():
    defs = HtmlFormatter(style=STYLE).get_style_defs(f"{SELECTOR} .highlight")
    rules = []
    for line in defs.splitlines():
        # a few rules come back unscoped (pre, linenos), so prefix those too
        if line.strip() and not line.startswith(SELECTOR):
            line = f"{SELECTOR} {line}"
        # let dark.css own the code block background
        line = line.replace("#0d1117", "var(--asc-surface)")
        rules.append(line)
    OUTPUT.write_text(HEADER + "\n".join(rules) + "\n")
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
