'use strict';

// Do this as the first thing so that any code reading it knows the right env.
process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';

// Makes the script crash on unhandled rejections instead of silently
// ignoring them. In the future, promise rejections that are not handled will
// terminate the Node.js process with a non-zero exit code.
process.on('unhandledRejection', (err) => {
  throw err;
});

// Ensure environment variables are read.
require('../config/env');

const webpack = require('webpack');
const WebpackDevServer = require('webpack-dev-server');
const colors = require('../config/devUtils/colors');
const clearConsole = require('../config/devUtils/clearConsole');
const checkRequiredFiles = require('../config/devUtils/checkRequiredFiles');
const checkBrowsers = require('../config/devUtils/checkBrowsers');
const {
  choosePort,
  createCompiler,
  prepareUrls,
} = require('../config/devUtils/devServerUtils');
const paths = require('../config/paths');
const configFactory = require('../config/webpack.config');
const createDevServerConfig = require('../config/webpackDevServer.config');

const isInteractive = process.stdout.isTTY;

// Warn and crash if required files are missing
if (!checkRequiredFiles([paths.appHtml, paths.appIndexJs])) {
  process.exit(1);
}

// Tools like Cloud9 rely on this.
const DEFAULT_PORT = parseInt(process.env.PORT, 10) || 3000;
const HOST = process.env.HOST || '0.0.0.0';

if (process.env.HOST) {
  console.log(
    colors.cyan(
      `Attempting to bind to HOST environment variable: ${colors.yellow(
        colors.bold(process.env.HOST)
      )}`
    )
  );
  console.log(
    `If this was unintentional, check that you haven't mistakenly set it in your shell.`
  );
  console.log();
}

// Builds webpack-dev-server's `open` option from the BROWSER environment
// variable: "none" disables opening a browser, unset opens the URL in the
// default browser, and anything else names the app to open it with
// (BROWSER_ARGS supplies extra whitespace-separated arguments).
function getOpenOption(url) {
  const browser = process.env.BROWSER;
  if (!browser) {
    return url;
  }
  if (browser.toLowerCase() === 'none') {
    return false;
  }
  const args = (process.env.BROWSER_ARGS || '').split(/\s+/).filter(Boolean);
  return { target: url, app: { name: browser, arguments: args } };
}

async function main() {
  // We require that you explicitly set browsers and do not fall back to
  // browserslist defaults.
  checkBrowsers(paths.appPath);

  // We attempt to use the default port but if it is busy, we offer the user to
  // run on a different port. `choosePort()` resolves to the next free port.
  const port = await choosePort(HOST, DEFAULT_PORT);
  if (port == null) {
    // We have not found a port.
    return;
  }

  const config = configFactory('development');
  const protocol = process.env.HTTPS === 'true' ? 'https' : 'http';
  const appName = require(paths.appPackageJson).name;

  const urls = prepareUrls(
    protocol,
    HOST,
    port,
    paths.publicUrlOrPath.slice(0, -1)
  );
  // Create a webpack compiler that is configured with custom messages.
  const compiler = createCompiler({ appName, config, urls, webpack });
  const { createProxyMiddleware } = await import('http-proxy-middleware');
  // Serve webpack assets generated by the compiler over a web server.
  const serverConfig = {
    ...createDevServerConfig({ createProxyMiddleware }),
    host: HOST,
    port,
    open: getOpenOption(urls.localUrlForBrowser),
  };
  const devServer = new WebpackDevServer(serverConfig, compiler);
  // Launch WebpackDevServer.
  devServer.startCallback(() => {
    if (isInteractive) {
      clearConsole();
    }
    console.log(colors.cyan('Starting the development server...\n'));
  });

  ['SIGINT', 'SIGTERM'].forEach(function (sig) {
    process.on(sig, function () {
      devServer.stop();
      process.exit();
    });
  });

  if (process.env.CI !== 'true') {
    // Gracefully exit when stdin ends
    process.stdin.on('end', function () {
      devServer.stop();
      process.exit();
    });
  }
}

main().catch((err) => {
  if (err && err.message) {
    console.log(err.message);
  }
  process.exit(1);
});
