---
# Modifications Copyright (c) 2023 Ctrl IQ, Inc.
name: Promote Release

env:
  LC_ALL: "C.UTF-8" # prevent ERROR: Ansible could not initialize the preferred locale: unsupported locale setting

on:
  release:
    types: [published]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  promote:
    if: endsWith(github.repository, '/ascender') 
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout ascender
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Get python version from Makefile
        run: echo py_version=`make PYTHON_VERSION` >> $GITHUB_ENV

      - name: Install python ${{ env.py_version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: ${{ env.py_version }}

      - name: Install dependencies
        run: |
          python${{ env.py_version }} -m pip install wheel twine setuptools-scm

#      - name: Set official collection namespace
#        run: echo collection_namespace=awx >> $GITHUB_ENV
#        if: ${{ github.repository_owner == 'ansible' }}

#      - name: Set official pypi info
#        run: echo pypi_repo=pypi >> $GITHUB_ENV
#        if: ${{ github.repository_owner == 'ansible' }}

#      - name: Set unofficial pypi info
#        run: echo pypi_repo=testpypi >> $GITHUB_ENV
#        if: ${{ github.repository_owner != 'ansible' }}

      - name: Log in to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

#      - name: Log in to Quay
#        run: |
#          echo ${{ secrets.QUAY_TOKEN }} | docker login quay.io -u ${{ secrets.QUAY_USER }} --password-stdin

      - name: Re-tag and promote awx image
        run: |
          docker pull ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
          docker tag ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }} ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest

#          docker pull ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
#          docker tag ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }} quay.io/${{ github.repository }}:${{ github.event.release.tag_name }}
#          docker tag ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }} quay.io/${{ github.repository }}:latest
#          docker push quay.io/${{ github.repository }}:${{ github.event.release.tag_name }}
#          docker push quay.io/${{ github.repository }}:latest
#          docker pull ghcr.io/${{ github.repository_owner }}/awx-ee:${{ github.event.release.tag_name }}
#          docker tag ghcr.io/${{ github.repository_owner }}/awx-ee:${{ github.event.release.tag_name }} quay.io/${{ github.repository_owner }}/awx-ee:${{ github.event.release.tag_name }}
#          docker push quay.io/${{ github.repository_owner }}/awx-ee:${{ github.event.release.tag_name }}
